### PR TITLE
SHOP-2148 Allow to flush cache partially

### PR DESCRIPTION
**Pull request by andriyanbobryk**
## Tasks fixed
- https://saxo-com.atlassian.net/browse/SHOP-2148

## Description
- Reset all cache call on API posibility added

### CODE REVIEW

**Review by pilgren — APPROVED** [review]

**Comment by pilgren** [comment]
Shouldn't this merge into `develop`?

**Comment by andriyanbobryk** [comment]
now develop

**Review by pilgren — CHANGES_REQUESTED** [review]
The Redis implementation is being moved in this task
https://saxo-com.atlassian.net/browse/SHOP-2194

Let's wait until that has been released and then moved this code as well - and implement this for the ServiceStack implementation as well

**Comment by pilgren** [comment]
These changes has been made in the `Saxo.Redis` repository

**Pull request closed without merging**
